In [ ]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

import warnings
warnings.filterwarnings("ignore")
#Please ignore the warnings with version change

from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive



Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
trainfile = r'/gdrive/My Drive/ASU_MSBA/CIS_508/Assignment2/TM/Portugese Bank Data - TRAIN.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r'/gdrive/My Drive/ASU_MSBA/CIS_508/Assignment2/TM/Portugese Bank Data - TEST.csv'
testData = pd.read_csv(testfile)  #creates a dataframe


print(trainData.shape)
print(testData.shape)



(4521, 17)
(45211, 17)


In [ ]:
trainData.info()

In [ ]:
testData.info()

In [ ]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']


In [ ]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['y']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['y']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(4521, 16)
(4521, 1)
Test Set shape:
(45211, 16)
(45211, 1)


In [ ]:
#DO ONE-HOT ENCODING ON CATEGORICAL VARIABLES==============================================
#The below function returns a list of categorical features which are not numeric. 
cat_cols = Xtrain.select_dtypes(exclude=['float','int']).columns #selecting the categorical columns
print(cat_cols.shape)
print(cat_cols)


(9,)
Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='object')


In [ ]:
#List of Categorical Features
categoricalFeatures = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome']


In [ ]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(Xtrain[categoricalFeatures]),columns=ohe.get_feature_names(),index=Xtrain.index)
Xtrain = pd.concat([Xtrain,Xcat],axis=1)
Xtrain.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtrain.sample(5)

age  balance  day  duration  ...  x8_failure  x8_other  x8_success  x8_unknown
26     55      627    5       247  ...         0.0       0.0         0.0         1.0
544    49     2465   20       157  ...         0.0       0.0         0.0         1.0
1059   57      808    7       274  ...         0.0       0.0         0.0         1.0
1010   23     8494   25       158  ...         0.0       0.0         0.0         1.0
471    55     -196   20       210  ...         0.0       0.0         0.0         1.0

[5 rows x 51 columns]

In [ ]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]),columns=ohe.get_feature_names(),index=Xtest.index)
Xtest = pd.concat([Xtest,Xcat],axis=1)
Xtest.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtest.sample(5)

age  balance  day  ...  x8_other  x8_success  x8_unknown
33661   33     1586   20  ...       0.0         0.0         1.0
30128   45      323    4  ...       1.0         0.0         0.0
19021   58     4725    5  ...       0.0         0.0         1.0
44944   24      368    7  ...       0.0         0.0         1.0
37077   39     1419   13  ...       1.0         0.0         0.0

[5 rows x 51 columns]

In [ ]:
#List of Categorical Features
categorical_Depndent_variable = ["y"]

In [ ]:
YTCat = pd.DataFrame(ohe.fit_transform(Ytrain[categorical_Depndent_variable]),columns=ohe.get_feature_names(),index=Ytrain.index)
Ytrain = pd.concat([Ytrain,YTCat],axis=1)
Ytrain.drop(labels=categorical_Depndent_variable,axis=1,inplace=True)
Ytrain.sample(5)

x0_no  x0_yes
2972    0.0     1.0
4295    1.0     0.0
2929    1.0     0.0
8       1.0     0.0
2957    1.0     0.0

In [ ]:
Ytrain = Ytrain.iloc[:,-1]
Ytrain.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: x0_yes, dtype: float64

In [ ]:
YtestCat = pd.DataFrame(ohe.fit_transform(Ytest[categorical_Depndent_variable]),columns=ohe.get_feature_names(),index=Ytest.index)
Ytest = pd.concat([Ytest,YtestCat],axis=1)
Ytest.drop(labels=categorical_Depndent_variable,axis=1,inplace=True)
Ytest.sample(5)

x0_no  x0_yes
17498    1.0     0.0
36596    1.0     0.0
12599    1.0     0.0
8824     1.0     0.0
21701    1.0     0.0

In [ ]:
Ytrain = Ytest.iloc[:,-1]
Ytest.head()

x0_no  x0_yes
0    1.0     0.0
1    1.0     0.0
2    1.0     0.0
3    1.0     0.0
4    1.0     0.0

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
Train_Pred = dt.predict(Xtrain)
Test_Pred = dt.predict(Xtest)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(Ytrain,Train_Pred))
print("Test Accuracy:", metrics.accuracy_score(Ytest,Test_Pred))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,Test_Pred))
print("Max Depth",dt.get_depth())
print("Leaf",dt.get_n_leaves())
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, Test_Pred))
clf_cv_score = cross_val_score(dt, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Train Accuracy: 1.0
Test Accuracy: 0.8835460396806087
Confusion Matrix for Decision Tree:
[[37236  2686]
 [ 2579  2710]]
Max Depth 28
Leaf 380
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

         0.0       0.94      0.93      0.93     39922
         1.0       0.50      0.51      0.51      5289

    accuracy                           0.88     45211
   macro avg       0.72      0.72      0.72     45211
weighted avg       0.88      0.88      0.88     45211

[0.67452381 0.64668269 0.72230769 0.70307692 0.68408654]


In [ ]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
X_Pred1 = rf.predict(Xtest)
XPred1 = rf.predict(Xtrain)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred1))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred1))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred1))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred1))
clf_cv_score = cross_val_score(rf, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Train Accuracy: 1.0
Test Accuracy: 0.9129194222644932
Confusion Matrix for Decision Tree:
[[39187   735]
 [ 3202  2087]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

         0.0       0.92      0.98      0.95     39922
         1.0       0.74      0.39      0.51      5289

    accuracy                           0.91     45211
   macro avg       0.83      0.69      0.73     45211
weighted avg       0.90      0.91      0.90     45211

[0.63824405 0.59389423 0.61269231 0.59764423 0.61206731]


Decision Tree: Random & Grid Search

In [ ]:
#Hyperparameter tuning done for decision tree classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,300,10),'max_depth': 
            range(5,30,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=5)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 20, 'max_depth': 5, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.897724
--- 1.797858476638794 seconds ---


In [ ]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree
{'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.896220
--- 54.35482621192932 seconds ---


In [ ]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier 
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

In [ ]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.8977240052199686
Confusion Matrix for Decision Tree:
[[39063   859]
 [ 3765  1524]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

         0.0       0.91      0.98      0.94     39922
         1.0       0.64      0.29      0.40      5289

    accuracy                           0.90     45211
   macro avg       0.78      0.63      0.67     45211
weighted avg       0.88      0.90      0.88     45211

[0.66883929 0.65451923 0.63884615 0.61375    0.6725    ]


In [ ]:
# Accuracy for Decision Tree using Grid Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtGrid_predict))
clf_cv_score = cross_val_score(dtGrid, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.8962199464732035
Confusion Matrix for Decision Tree:
[[38959   963]
 [ 3729  1560]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

         0.0       0.91      0.98      0.94     39922
         1.0       0.62      0.29      0.40      5289

    accuracy                           0.90     45211
   macro avg       0.77      0.64      0.67     45211
weighted avg       0.88      0.90      0.88     45211

[0.67133929 0.65264423 0.62336538 0.62629808 0.65639423]


In [ ]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')

Test Accuracy: 0.8962199464732035
Confusion Matrix for Decision Tree:
[[38959   963]
 [ 3729  1560]]
Printing the precision and recall, among other metrics


Random Forest: Random & Grid Search

In [ ]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth': 
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 30, 'min_samples_leaf': 30, 'max_features': 20, 'max_depth': 9}
accuracy Score for Decision Tree:0.901042
--- 14.800294876098633 seconds ---


In [ ]:
import time
start_time = time.time()

print("GridSearchCV-Random Forest")
rf_grid = GridSearchCV(rf,rand_parameters)
rf_grid.fit(Xtrain, Ytrain)
grid_parm1=rf_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Random Forest
{'max_depth': 5, 'max_features': 20, 'min_samples_leaf': 10, 'n_estimators': 20}
accuracy Score for Decision Tree:0.901882
--- 224.64285373687744 seconds ---


In [ ]:
#Using the parameters obtained from HyperParameterTuning in the RandomForestClassifier 
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(Xtrain,Ytrain)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(Xtrain,Ytrain)
rfGrid_predict = rfGrid.predict(Xtest)

In [ ]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfRand_predict))
clf_cv_score = cross_val_score(rfRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.8999358563181526
Confusion Matrix for Decision Tree:
[[39154   768]
 [ 3756  1533]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

         0.0       0.91      0.98      0.95     39922
         1.0       0.67      0.29      0.40      5289

    accuracy                           0.90     45211
   macro avg       0.79      0.64      0.67     45211
weighted avg       0.88      0.90      0.88     45211

[0.64113095 0.62211538 0.63067308 0.61206731 0.60725962]


In [ ]:
# Accuracy for Decision Tree using Grid Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))
clf_cv_score = cross_val_score(rfGrid, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.9009754263342992
Confusion Matrix for Decision Tree:
[[38999   923]
 [ 3554  1735]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

         0.0       0.92      0.98      0.95     39922
         1.0       0.65      0.33      0.44      5289

    accuracy                           0.90     45211
   macro avg       0.78      0.65      0.69     45211
weighted avg       0.89      0.90      0.89     45211

[0.63761905 0.58634615 0.63360577 0.59346154 0.61019231]
